### ISSUE TITLE
[BUG] bluetooth not working on pizero2

### ISSUE THREAD

**Issue by Sniffleupagus** [Sniffleupagus/pwnagotchi-snflpgs#1]
BT apparently not working.

**To Reproduce**
unsure. someone told me about it.

**Comment by TQMatvey** [comment]
hey, i wanna try building and testing your fork, how is rpiz2w working? internal nexmon fw works well or has issues like original? rn across all forks i tested, only aluminum-ice's fork seems to properly support it.

**Comment by Sniffleupagus** [comment]
I haven't checked out the Bluetooth issue yet. Otherwise the second image works on pizero2w.
It uses the same nexmon as all the others, so should be the same reliability. Seems kind of random. Like sometimes it goes more than a day without going blind. Sometimes it's just a few hours.

**Comment by Sniffleupagus** [comment]
Figured it out and updated. It was a bug in the launcher script, trying to run bluetoothd from /usr/lib instead of /usr/libexec.  Fixed in the repo.
